(function ensightenInit(){var ensightenOptions = {client: "bhfoto", clientId: 1084, publishPath: "apertureprod", bootstrapVersion: "v11", isPublic:0, serverComponentLocation: "nexus.ensighten.com/bhfoto/apertureprod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/bhfoto/apertureprod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Nov 27 15:32:22 GMT 2025", beaconSamplingSeedValue: 11, dataLayerName: "ensDataLayer"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(l){function q(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+" is missing"}function r(a){this.name="BeaconException";this.message="There was an error during beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function u(){for(var a=e.dataDefinitionIds.length,b=!0,d=0;d<a;d++){var f=e.dataDefinitions[e.dataDefinitionIds[d]];if(!f||
null==f.endRegistration){b=!1;break}}b&&e.callOnDataDefintionComplete()}var c={},e={};e.ensightenOptions=ensightenOptions;e.scDataObj={};var z="",w=null;if(document.currentScript&&document.currentScript.src){var n=document.currentScript.src;/^[A-Za-z][A-Za-z0-9+.-]*:/.test(n)||(n.startsWith("//")||(n="//"+n),n=window.location.protocol+n);n=new URL(n);z=n.hostname;n=n.pathname;n.startsWith(`/${ensightenOptions.client}/${ensightenOptions.publishPath}/sha`)&&(w=n.split("/"),w=w[w.length-2]||null)}c.version=
"1.26.0";c.getDynamicDomain=function(){if(z)return z;for(var a=null,b=document.getElementsByTagName("script"),d=l.client+"/"+l.publishPath+"/Bootstrap.js",f=l.client+"/Bootstrap.js",h=0;h<b.length;h++)if(-1<b[h].src.indexOf(d)||"prod"==l.publishPath&&-1<b[h].src.indexOf(f)){a=b[h];break}return a?(b=document.createElement("a"),b.href=a.getAttribute("src"),b.hostname):""};ensightenOptions.nexus=c.nexus=ensightenOptions.nexus||c.getDynamicDomain()||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();
c.options={interval:l.interval||100,erLoc:l.errorLocation||c.nexus+"/error/e.gif",scLoc:l.serverComponentLocation||c.nexus+"/"+l.client+"/serverComponent.php",sjPath:l.staticJavascriptPath||c.nexus+"/"+l.client+"/code/",alLoc:l.alertLocation||c.nexus+"/alerts/a.gif",publishPath:l.publishPath,isPublic:l.isPublic,client:l.client,clientId:l.clientId,enableTagAuditBeacon:l.enableTagAuditBeacon,beaconSamplingSeedValue:l.beaconSamplingSeedValue||-1,dataLayerName:l.dataLayerName||"ensDataLayer",protocol:"http:"===
window.location.protocol?window.location.protocol:"https:",sriPath:w};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.appIdWhitelist=[];c.appIdBlacklist=[];window[c.options.dataLayerName]&&window[c.options.dataLayerName][0]&&(window[c.options.dataLayerName][0]["ens.whitelist"]&&(c.appIdWhitelist=window[c.options.dataLayerName][0]["ens.whitelist"]),window[c.options.dataLayerName][0]["ens.blacklist"]&&(c.appIdBlacklist=window[c.options.dataLayerName][0]["ens.blacklist"]));
c.canRuleRunByAppId=function(a){return a?a&&!a.appId||a&&-1==a.appId||0==c.appIdWhitelist.length&&0==c.appIdBlacklist.length?!0:0<c.appIdWhitelist.length&&0==c.appIdBlacklist.length?-1==c.appIdWhitelist.indexOf(a.appId)?!1:!0:0==c.appIdWhitelist.length&&0<c.appIdBlacklist.length?-1==c.appIdBlacklist.indexOf(a.appId)?!0:!1:0<c.appIdWhitelist.length&&0<c.appIdBlacklist.length&&-1==c.appIdBlacklist.indexOf(a.appId)&&-1!=c.appIdWhitelist.indexOf(a.appId)?!0:!1:!1};c.test=function(a){if(c.canRuleRunByAppId(a)&&
!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};q.prototype=Error();q.prototype||(q.prototype={});q.prototype.constructor=q;c.DependencyNotAvailableException=q;r.prototype=Error();r.prototype||(r.prototype={});r.prototype.constructor=r;c.BeaconException=r;c.checkForInvalidDependencies=function(a,b,d,f){for(var h=0;h<d.length;h++)if("DEPENDENCYNEVERAVAILABLE"===d[h])return e.currentRuleId=
a,e.currentDeploymentId=b,e.reportException(new c.DependencyNotAvailableException(f[h])),b&&-1!==b&&c.allDeploymentIds.push(b),!0;return!1};e.currentRuleId=-1;e.currentDeploymentId=-1;e.reportedErrors=[];e.reportedAlerts=[];e.AF=[];c.initialized=!1;e.extend=function(a){c.initialized&&window[ensightenOptions.ns].reportException({name:"CoreExtendException",message:"Core extend was called after initialization"})};e.initialize=function(){c.initialized||(this.extend(c),c.initialized=!0)};e.sampleBeacon=
function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(f){}return a};e.getServerComponent=function(a){e.callOnGetServerComponent();var b=c.options.protocol+"//"+("/"==c.options.scLoc.charAt(0)?c.getDynamicDomain():"")+c.options.scLoc;c.options.sriPath&&(b=b.replace("/serverComponent.php",`/${c.options.sriPath}/serverComponent.php`));a=c.constructScUrl(b,a||!0);fetch(a).then(d=>d.ok?d.json():(window[ensightenOptions.ns].reportException({name:"getServerComponentException",
message:"Network response was not ok"}),{})).then(d=>{c.process(d)}).catch(d=>{window[ensightenOptions.ns].reportException({name:"getServerComponentException",message:"There was a problem with the fetch operation:"+d})})};c.constructScUrl=function(a,b){b=1==b&&"object"==typeof e.scDataObj?e.scDataObj:b;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));var d=window.location.href;"object"===typeof b&&b.PageID&&(d=b.PageID,delete b.PageID);if("object"===typeof b)for(i in b){var f=~d.indexOf("#")?
d.slice(d.indexOf("#"),d.length):"";d=d.slice(0,f.length?d.length-f.length:d.length);d+=~d.indexOf("?")?"&":"?";for(k in b)d+=k+"="+b[k]+"&";d=d.slice(0,-1)+f;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";return a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")};c.process=function(a){a.pageFiles&&Array.isArray(a.pageFiles)&&0<
a.pageFiles.length&&e.insertPageFiles(a.pageFiles);a.dataDefinitionIds&&Array.isArray(a.dataDefinitionIds)&&0<a.dataDefinitionIds.length&&e.setPageSpecificDataDefinitionIds(a.dataDefinitionIds)};e.setVariable=function(a,b){c.ensightenVariables[a]=b};e.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};e.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};e.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,
readyForServerComponent:!1};e.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=c.options.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(a.rid||e.currentRuleId||
-1)+"&did="+encodeURIComponent(a.did||e.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=e.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a);e.currentRuleId=-1;e.currentDeploymentId=-1};e.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);e.currentRuleId=this.id;e.currentDeploymentId=this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&
(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),e.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.appId=a.appId;this.executionData={hasRun:!1,runTime:[]}};c.updateRuleEvent=function(a,b){for(var d=0;d<c.ruleList.length;d++)if(null!=c.ruleList[d].eventTriggerObj&&c.ruleList[d].eventTriggerObj.rid==a)return c.ruleList[d].id=a,c.ruleList[d].deploymentId=b,c.ruleList[d].executionData.hasRun=!0,c.ruleList[d].executionData.runTime=
[new Date],c.allDeploymentIds.push(b),c.runDeploymentIds.push(b),c.runRuleIds.push(a),!0;return!1};e.triggerEvent=function(a,b){e.getRule(a)||c.updateRuleEvent(a,b)||window[ensightenOptions.ns].reportException({rid:a,did:b,name:"triggerEvent error",message:"rid not found in rule.eventTriggerObj in registered rule list. Dependent Tag can not run due to missing event object."})};e.registerRule=function(a){if(e.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);
e.testAll();return!0};e.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};e.getRuleList=function(){return c.ruleList};e.clearRuleList=function(){c.ruleList=[]};e.getAllDeploymentIds=function(){return c.allDeploymentIds};e.getRunRuleIds=function(){return c.runRuleIds};e.getRunDeploymentIds=function(){return c.runDeploymentIds};e.hasRuleRun=function(a){return(a=e.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};e.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};e.generateAlert=function(a){a=
e.imageRequest(c.options.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+e.currentRuleId+"&did="+e.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};e.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};e.insertScript=function(a,b,d,f){var h=document.getElementsByTagName("script"),g;if(void 0!==b?b:1)for(g=0;g<
h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(!f)var m=d;else if(d){d=1==d&&"object"==typeof e.scDataObj?e.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;"object"===typeof d&&d.PageID&&(b=d.PageID,delete d.PageID);if("object"===typeof d)for(g in d){g=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,g.length?b.length-g.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in d)b+=k+"="+d[k]+
"&";b=b.slice(0,-1)+g;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(b)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")}(function(t,p,A){var v=p.head||p.getElementsByTagName("head"),B=function(){if("item"in v){if(!v[0]){setTimeout(B,25);return}v=v[0]}var x=p.createElement("script"),y;for(y in m)x.setAttribute(y,m[y]?m[y]:null);
A&&(x.src=A);x.onload=x.onerror=function(){this.addEventListener&&(this.readyState="loaded")};v.insertBefore(x,v.firstChild)};setTimeout(B,0)})(window,document,a,m)};e.loadScriptCallback=function(a,b,d,f,h){var g=document.getElementsByTagName("script"),m=g[0];h=h||!1;if(d)for(d=0;d<g.length;d++)if(g[d].src===a&&g[d].readyState&&/loaded|complete/.test(g[d].readyState))try{b()}catch(p){window[ensightenOptions.ns].reportException(p)}finally{return}g=document.createElement("script");for(var t in f)g.setAttribute(t,
f[t]?f[t]:null);g.type="text/javascript";g.async=!0;g.src=a;g.onerror=function(){this.addEventListener&&(this.readyState="loaded")};g.onload=g.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(p){window[ensightenOptions.ns].reportException(p)}}};h?(a=document.head||document.getElementsByTagName("head")[0],a.insertBefore(g,a.firstChild)):
m.parentNode.insertBefore(g,m)};e.insertPageFiles=function(a){var b=0,d=0,f=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)if("string"===typeof a[b])window[ensightenOptions.ns].loadScriptCallback(a[b],f);else{const {src:h,integrity:g}=a[b];window[ensightenOptions.ns].loadScriptCallback(h,f,!1,g?{integrity:g,crossorigin:"anonymous"}:{},!0)}};e.unobtrusiveAddEvent=function(a,b,d){try{var f=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,
arguments);return f.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};e.anonymous=function(a,b){return function(){try{e.currentRuleId=b?b:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};e.setCurrentRuleId=function(a){e.currentRuleId=a};e.setCurrentDeploymentId=function(a){e.currentDeploymentId=a};c.bind=function(a,b,d,f,h,g){if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:d||-1,appId:f||-1,dependencies:"immediate"==h?[]:[function(){return window[ensightenOptions.ns].executionState[h]}],
code:a}),null!=g&&(a.eventTriggerObj=g);else if("object"!==typeof a)return!1;e.registerRule(a)};e.bindImmediate=function(a,b,d,f){c.bind(a,b,d,f,"immediate")};e.bindDOMParsed=function(a,b,d,f){c.bind(a,b,d,f,"DOMParsed")};e.bindDOMLoaded=function(a,b,d,f){c.bind(a,b,d,f,"DOMLoaded")};e.bindPageSpecificCompletion=function(a,b,d,f){c.bind(a,b,d,f,"conditionalRules")};e.bindOnGetServerComponent=function(a,b,d,f){c.bind(a,b,d,f,"readyForServerComponent")};e.bindDataDefinitionComplete=function(a,b,d,f){c.bind(a,
b,d,f,"dataDefinitionComplete")};e.checkHasRun=function(a){if(0===a.length)return!0;for(var b,d=0;d<a.length;++d)if(b=e.getRule(parseInt(a[d],10)),!b||!b.executionData.hasRun)return!1;return!0};c.bindDependency=function(a,b,d,f,h,g,m,t){var p=[];if(!c.checkForInvalidDependencies(b,f,d,h)){"immediate"==!m&&p.push(function(){return window[ensightenOptions.ns].executionState[m]});p.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:f||
-1,appId:g||-1,dependencies:p,code:a}),null!=t&&(a.eventTriggerObj=t);else if("object"!==typeof a)return!1;e.registerRule(a)}};e.bindDependencyImmediate=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"immediate")};e.bindDependencyDOMLoaded=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"DOMLoaded")};e.bindDependencyDOMParsed=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"DOMParsed")};e.bindDependencyPageSpecificCompletion=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"conditionalRules")};
e.bindDependencyOnGetServerComponent=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"readyForServerComponent")};e.bindDependencyDataDefinitionComplete=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"dataDefinitionComplete")};e.dataDefinitionIds=[];e.dataDefinitions=[];e.pageSpecificDataDefinitionsSet=!1;e.setPageSpecificDataDefinitionIds=function(a){for(var b=a?a.length:0,d=0;d<b;d++){var f=a[d];if(Array.prototype.indexOf)-1==e.dataDefinitionIds.indexOf(f)&&e.dataDefinitionIds.push(f);else{for(var h=
!1,g=e.dataDefinitionIds.length,m=0;m<g;m++)if(e.dataDefinitionIds[m]===f){h=!0;break}h||e.dataDefinitionIds.push(f)}}e.pageSpecificDataDefinitionsSet=!0;u()};e.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};e.registerDataDefinition=function(a,b){var d=e.dataDefinitions[b];d||(d=new e.DataDefinition(b,
a),e.dataDefinitions[b]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());e.pageSpecificDataDefinitionsSet&&u()};e.callOnDataDefintionComplete=function(){e.executionState.dataDefinitionComplete=!0;e.testAll()};e.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};e.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};e.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};e.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};e.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};e.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};e.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var C=function(){var a=[],b=!1,d=!1;return{add:function(f){b&&!d?f():"function"==typeof f&&(a[a.length]=
f)},exec:function(){d=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};e.new_fArray=function(){return C()};c.timer=null;(function(){function a(f,h){return function(){f.apply(h,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=
a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),e.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",e.callOnDOMParsed,!1),window.addEventListener("load",e.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document,b=function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(b,15);return}window[ensightenOptions.ns].callOnDOMParsed()};b()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(e.executionState.DOMParsed=!0,e.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&e.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,d,f,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],f=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+f,a.push(h);b="["+a.join(";")+"]";var m=c.options.protocol+"//"+c.nexus+"/"+encodeURIComponent(l.client)+"/"+encodeURIComponent(l.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(l.clientId)+"&data="+b+"&idx=0&r="+c.rand;e.imageRequest(m)}catch(t){e.currentRuleId=-1,e.currentDeploymentId=-1,a=
new c.BeaconException(t),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(e.testAll,c.options.interval);return e}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var l=window.performance;if(l){l=l.timing||{};var q=l.navigationStart||0,r={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var u="&ns="+encodeURIComponent(l.navigationStart);for(var c in r)if(void 0!==l[c]){var e=l[c]-q;u+="&"+r[c]+"="+(0<e?encodeURIComponent(e):0)}else u+="&"+r[c]+"=-1";window[ensightenOptions.ns].timing=u;c=ensightenOptions.nexus||"nexus.ensighten.com";l=ensightenOptions.staticJavascriptPath||
"";u=l.indexOf("/",0);q=l.indexOf("/code/");l=l.substring(u,q)+"/perf.rnc";l+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+l)}}});

const _public=window[ensightenOptions.ns],extend=_public.extend;
_public.extend=function(b){extend(b);b.ruleEventList=[];b.hasObjectWithRuleIdAndEventName=function(c){return b.ruleEventList.some(function(a){return a.ruleId===c.ruleId&&a.eventName===c.eventName})};b.registerRuleEvent=function(c,a){var f=[];Array.isArray(a)&&a.forEach(function(e){var d={ruleId:c,eventName:e};b.hasObjectWithRuleIdAndEventName(d)||(f.push(e),b.ruleEventList.push(d))});return f};b.bindEvents=function(c,a,f,e,d,g){var h=b.registerRuleEvent(a,d);0<h.length&&(-1==a?b.bind(c,-1,-1,e,g):
b.bind(function(){window[ensightenOptions.ns].ensEvent.add(h,c)},-1,-1,e,g,{eventTrigger:!0,rid:a,did:f}))};_public.ensEvent=_public.ensEvent||{};_public.ensEvent.setRuleEventList=function(c){b.ruleEventList=JSON.parse(JSON.stringify(c))};_public.ensEvent.clearRuleEventList=function(){b.ruleEventList=[]};_public.ensEvent.getRuleEventList=function(){return b.ruleEventList};_public.bindEventImmediate=function(c,a,f,e,d){b.bindEvents(c,a,f,e,d,"immediate")};_public.bindEventDOMParsed=function(c,a,f,
e,d){b.bindEvents(c,a,f,e,d,"DOMParsed")};_public.bindEventDOMLoaded=function(c,a,f,e,d){b.bindEvents(c,a,f,e,d,"DOMLoaded")};b.bindEventDependency=function(c,a,f,e,d,g,h,l){var k=b.registerRuleEvent(a,l);0<k.length&&(-1==a?b.bindDependency(c,-1,d,-1,d,g,h):b.bindDependency(function(){window[ensightenOptions.ns].ensEvent.add(k,c)},-1,f,-1,d,g,h,{eventTrigger:!0,rid:a,did:e}))};_public.bindEventDependencyImmediate=function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"immediate",h)};_public.bindEventDependencyDOMLoaded=
function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"DOMLoaded",h)};_public.bindEventDependencyDOMParsed=function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"DOMParsed",h)}};
window[ensightenOptions.ns].initialize();
/*
 MIT License (c) copyright 2013 original author or authors */
window[ensightenOptions.ns].data||(window[ensightenOptions.ns].when=function(){function e(g,l,t,w){return v(g).then(l,t,w)}function B(g){this.then=g}function v(g){return f(function(l){l(g)})}function f(g){function l(z){C&&(x=d(z),b(C,x),C=y)}function t(z){l(k(z))}function w(z){C&&b(C,a(z))}var x,C=[];try{g(l,t,w)}catch(z){t(z)}return new B(function(z,F,G){return f(function(H,N,I){C?C.push(function(L){L.then(z,F,G).then(H,N,I)}):n(function(){x.then(z,F,G).then(H,N,I)})})})}function d(g){return g instanceof
B?g:g!==Object(g)?r(g):f(function(l,t,w){n(function(){try{var x=g.then;"function"===typeof x?T(x,g,l,t,w):l(r(g))}catch(C){t(C)}})})}function r(g){var l=new B(function(t){try{return"function"==typeof t?d(t(g)):l}catch(w){return k(w)}});return l}function k(g){var l=new B(function(t,w){try{return"function"==typeof w?d(w(g)):l}catch(x){return k(x)}});return l}function a(g){var l=new B(function(t,w,x){try{return"function"==typeof x?a(x(g)):l}catch(C){return a(C)}});return l}function b(g,l){n(function(){for(var t,
w=0;t=g[w++];)t(l)})}function c(g,l,t,w,x){p(2,arguments);return e(g,function(C){return f(function(z,F,G){function H(M){P(M)}function N(M){Q(M)}var I;var L=C.length>>>0;var O=Math.max(0,Math.min(l,L));var R=[];var W=L-O+1;var U=[];if(O){var P=function(M){U.push(M);--W||(Q=P=q,F(U))};var Q=function(M){R.push(M);--O||(Q=P=q,z(R))};for(I=0;I<L;++I)I in C&&e(C[I],N,H,G)}else z(R)}).then(t,w,x)})}function h(g,l,t,w){p(1,arguments);return u(g,A).then(l,t,w)}function u(g,l){return e(g,function(t){return f(function(w,
x,C){var z,F;var G=z=t.length>>>0;var H=[];if(G){var N=function(I,L){e(I,l).then(function(O){H[L]=O;--G||w(H)},x,C)};for(F=0;F<z;F++)F in t?N(t[F],F):--G}else w(H)})})}function n(g){1===E.push(g)&&K(m)}function m(){for(var g,l=0;g=E[l++];)g();E=[]}function p(g,l){for(var t,w=l.length;w>g;)if(t=l[--w],null!=t&&"function"!=typeof t)throw Error("arg "+w+" must be a function");}function q(){}function A(g){return g}e.defer=function(){var g,l;var t={promise:y,resolve:y,reject:y,notify:y,resolver:{resolve:y,
reject:y,notify:y}};t.promise=g=f(function(w,x,C){t.resolve=t.resolver.resolve=function(z){if(l)return v(z);l=!0;w(z);return g};t.reject=t.resolver.reject=function(z){if(l)return v(k(z));l=!0;x(z);return g};t.notify=t.resolver.notify=function(z){C(z);return z}});return t};e.resolve=v;e.reject=function(g){return e(g,k)};e.join=function(){return u(arguments,A)};e.all=h;e.map=u;e.reduce=function(g,l){var t=T(V,arguments,1);return e(g,function(w){var x=w.length;t[0]=function(C,z,F){return e(C,function(G){return e(z,
function(H){return l(G,H,F,x)})})};return X.apply(w,t)})};e.any=function(g,l,t,w){return c(g,1,function(x){return l?l(x[0]):x[0]},t,w)};e.some=c;e.isPromise=function(g){return g&&"function"===typeof g.then};B.prototype={otherwise:function(g){return this.then(y,g)},ensure:function(g){function l(){return v(g())}return this.then(l,l).yield(this)},yield:function(g){return this.then(function(){return g})},spread:function(g){return this.then(function(l){return h(l,function(t){return g.apply(y,t)})})},always:function(g,
l){return this.then(g,g,l)}};var y;var E=[];var D=setTimeout;var K="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(g){D(g,0)};var J=Function.prototype;var S=J.call;var T=J.bind?S.bind(S):function(g,l){return g.apply(l,V.call(arguments,2))};J=[];var V=J.slice;var X=J.reduce||function(g){var l=0;var t=Object(this);var w=t.length>>>0;var x=arguments;if(1>=x.length)for(;;){if(l in
t){x=t[l++];break}if(++l>=w)throw new TypeError;}else x=x[1];for(;l<w;++l)l in t&&(x=g(x,t[l],l,t));return x};return e}(),function(){function e(d,r){return v.all(r||[],function(k){return d.apply(null,k)})}function B(d){var r=f.call(arguments,1);return function(){return e(d,r.concat(f.call(arguments)))}}var v=window[ensightenOptions.ns].when;var f=[].slice;v.apply=e;v.call=function(d){return e(d,f.call(arguments,1))};v.lift=B;v.bind=B;v.compose=function(d){var r=f.call(arguments,1);return function(){var k=
f.call(arguments);k=e(d,k);return v.reduce(r,function(a,b){return b(a)},k)}}}(),window[ensightenOptions.ns].data=function(e,B){function v(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var f={engines:{memory:{get:function(a){if(d.utils.isArray(a)){for(var b=[],c=0;c<a.length;c++)b.push(f.data[a[c]]);return e[ensightenOptions.ns].when.resolve(b)}b=f.dataDefinitions[a]||{storage:{get:function(){}}};b=b.storage.get(b);f.data[a]=
b;return e[ensightenOptions.ns].when.resolve(f.data[a])},set:function(a,b){if(d.utils.isArray(a))for(var c in a)f.data[a[c]]=b[c];else f.data[a]=b;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(d.utils.isArray(a))for(var b in a)delete f.data[a[b]];else delete f.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){f.data={};f.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(f.data)}}},
normalizeInputArgs:function(a,b){var c={key:[],val:B},h;if(d.utils.isPlainObject(a))for(h in c.val=[],a)c.key.push(h),c.val.push(a[h]);else d.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},d={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},r=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};
v.prototype=Error();v.prototype||(v.prototype={});v.prototype.constructor=v;f.DataDefinitionException=v;f.checkForInvalidDataDefinitions=function(a){d.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a)),!0):!1};f.collectAvailableDataDefinitions=function(a){for(var b=[],c=0;c<a.length;c++){var h=parseInt(a[c],10),u=e[ensightenOptions.ns].dataDefinitions[h];if(null===u||u===B)if(u=d.storage.session.get({id:h}),
null!==u&&u!==B)d.set(h,u),f.dataDefinitions[h]={id:h,load:"visitor",storage:d.storage.visitor,missingDDFromCache:!0},b.push(e[ensightenOptions.ns].data.get(""+h));else return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Invalid data definition used: "+h)),{promises:[],isInvalid:!0};else b.push(e[ensightenOptions.ns].data.get(""+a[c]))}return{promises:b,isInvalid:!1}};f.getSync=function(a){function b(q){var A=q.extract||h,y=q.transform||u,E=!1,D=null,K=null;try{D=A()}catch(J){D=
null,E=!0}try{K=y(D)}catch(J){K=null,E=!0}E&&c.push(q.id);return K}var c=[],h=function(){return document},u=function(q){return null!==q&&q!==B?q.toString():null},n=parseInt(a);a="string"===typeof a?a.split("."):[];var m={},p="";if(!isNaN(n)&&"undefined"===typeof f.dataDefinitions[n])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(n,"Error resolving data definition: "+n+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(n)&&
"undefined"===typeof f.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),"Data definition specified does not exist on the page";isNaN(n)?3==a.length&&(m=d.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):m=d.getDataDefinitionById(n);p=m.load&&m.load.match(/(session|visitor)/i)&&m.storage&&m.storage.get?m.storage.get(m):
b(m);0<c.length&&e[ensightenOptions.ns].reportException(new f.DataDefinitionException(c,"Error resolving data definitions synchronously: "+c));return p};f.dataDefinitions={};f.dataDefinitionsBySourceCollName={};d.defineEngine=function(a,b){var c=["get","set","remove","clear","all"];f.engines[a]=b;if(!b.returnsPromise)for(a=0;a<c.length;a++){var h=c[a];b[h]=e[ensightenOptions.ns].when.lift(b[h])}};d.storage={instance:{set:function(a,b){},get:function(a){return f.getSync(a.id)}},page:{set:function(a,
b){},get:function(a){return f.data[a.id]}},session:{set:function(a,b){var c=d.storage.session.get({id:a}),h=new Date,u=h.getTime();h.setTime(u+18E5);null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:h.toGMTString()});b={expires:h.getTime(),value:b};e[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var b=e[ensightenOptions.ns].data.cookie.utils.get(a.id),c=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON;c=c||{};var h=new Date;h=h.getTime();if(null===
b){try{var u=c.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(n){u=null}null!=u&&(u.expires=+u.expires,h<=u.expires?b=u.value:""==u.expires&&u.value!=B?b=u.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var c=d.storage.session.get({id:a});null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return d.storage.session.get(a)}}};d.getEngine=
d.engine=function(a){return a?f.engines[a]||{get:r,set:r,remove:r,clear:r,all:r}:f.engines};d.all=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").all()};d.get=function(a,b,c){b=b||"memory";c=c||{};-1<a.indexOf(",")?(a=a.split(","),a=f.normalizeInputArgs(a)):a=f.normalizeInputArgs(a);return c.wait?f.getWait(a.key,e[ensightenOptions.ns].data.engine(b),c):f.data&&f.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(b).get(a.key):f.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(b),
c)};f.getWait=function(a,b,c){var h=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var p=b.get(a);if(-1===c.wait)return p;p.then(function(q){c.setCheck(q)?u.resolve(q):setTimeout(m,c.interval)},function(q){setTimeout(m,c.interval)})},m=function(){var p=+new Date-h;-1!==c.wait&&p<c.wait?n():u.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;d.utils.isArray(a)?c.setCheck=c.setCheck||function(p){for(var q=!0,A=0;A<p.length;A++)q=q&&!!p[A];return q}:c.setCheck=c.setCheck||
function(p){return!!p};n();return u.promise};f.getWaitForKey=function(a,b,c){var h=e[ensightenOptions.ns].when.defer(),u=function(){if(f.data&&f.data.hasOwnProperty(a)){var m=b.get(a);if(-1===c.wait)return m;m.then(function(p){h.resolve(p)},function(p){h.reject(p)})}else setTimeout(n,c.interval)},n=function(){u()};c.interval=c.interval||100;c.wait=c.wait||1;u();return h.promise};d.set=function(a,b,c){var h=f.normalizeInputArgs(a,b);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(c||
"memory").set(h.key,h.val)};d.remove=function(a,b){return e[ensightenOptions.ns].data.engine(b||"memory").remove(a)};d.clear=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").clear()};d.define=function(a,b){b&&(a.name=b.id||b.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};
a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=d.storage[b.toLowerCase()]||d.storage.page;a.resolved=!1;var c=a.extract||function(){return document},h=a.transform||function(p){return p},u=function(p,q){var A=[];A.push(a.persist.set(p,q));a.storage.set(a.id,q);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(p,q,a.collection);e[ensightenOptions.ns].when.all(A).then(function(y){n.resolve(y)},
function(y){n.reject(y)})},n=e[ensightenOptions.ns].when.defer();try{var m=a.trigger()}catch(p){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+p+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),m=e[ensightenOptions.ns].data.bottomOfBodyTrigger()}m.then(function(){var p=n,q=p.resolve,A=e[ensightenOptions.ns].when,y=A.reduce;try{var E=c()}catch(D){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,
'"'+D+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),E=null}q.call(p,y.call(A,[E,function(){try{return h.apply(this,arguments)}catch(D){return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+D+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},u],function(D,K,J,S){a.resolved=!0;if(1==J)return K(D);2==J&&K(a.name,D)}))},function(p){n.reject(p)});f.dataDefinitions[a.id]=a;f.dataDefinitionsBySourceCollName[""+
a.source+"."+a.collection+"."+a.dataDefName]=a;return n.promise};d.checkConditions=function(a){var b,c={lt:function(n,m){var p=+n,q=+m;return isNaN(p)||isNaN(q)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+n+", compareTo: "+m)),!1):p<q},gt:function(n,m){var p=+n,q=+m;return isNaN(p)||isNaN(q)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
n+", compareTo: "+m)),!1):p>q},eql:function(n,m){return n==m},exists:function(n,m){return n===B?!1:!0},re:function(n,m,p){m=new RegExp(m,p?"i":"");try{return n.match(m)}catch(q){return!1}},starts:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,"^"+m,p)},ends:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,m+"$",p)},contains:function(n,m,p){m=d.utils.escapeRegEx(m);return c.re(n,".*"+m+".*",p)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=c.gt;c["is less than"]=
c.lt;c.matches=c.re;for(b=0;b<a.values.length;b++){var h=a.customComparator?a.customComparator[b]?a.customComparator[b]:c[a.comparators[b]]:c[a.comparators[b]],u=h(a.values[b],a.compareTo[b],a.caseInsensitive?a.caseInsensitive[b]||!1:!1);a.not[b]&&(u=!u);if(!u&&h!=c.exists)return!1}return!0};d.triggerPromise=function(a,b,c){c=c||5E3;var h=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var m=a();m!=b?u.resolve(m):+new Date-h<c?setTimeout(n,200):u.reject("timed out")};n();return u.promise};
d.timeoutPromise=function(a,b){var c=e[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};d.delayTrigger=function(a){a=a||10;var b=e[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};d.delayUntilTrigger=function(a,b,c,h){c=c||null;h=h||200;var u=+new Date,n=e[ensightenOptions.ns].when.defer(),m=function(){var p=a();p!=b?n.resolve(p):c?+new Date-u<c?setTimeout(m,h):n.reject("timed out"):
setTimeout(m,h)};m();return n.promise};f.applyTrigger=function(a){var b=e[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};d.immediateTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindImmediate)};d.bottomOfBodyTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};d.whenValueExistsTrigger=function(){return e[ensightenOptions.ns].when.resolve(this.extract())};d.afterEnsightenCompleteTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};
d.afterElementsDownloadedTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};d.getAllDataDefinitionsOnCurrentPage=function(){return f.dataDefinitions};d.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return f.dataDefinitionsBySourceCollName};d.getDataDefinitionById=function(a){return f.dataDefinitions[a||-1]||{}};d.getDataDefinitionBySourceCollectionName=function(a,b,c){return f.dataDefinitionsBySourceCollName[""+a+"."+b+"."+c]||{}};d.getDataDefinitionByPercentSyntax=
function(a){a=(""+a).split("_");return 1>a.length?{}:f.dataDefinitions[a[1]]||{}};d.resolve=function(a,b){var c=this,h=null;if(!f.checkForInvalidDataDefinitions(a))if(b)e[ensightenOptions.ns].bindDataDefinitionComplete(function(){var m=f.collectAvailableDataDefinitions(a);m.isInvalid||e[ensightenOptions.ns].when.all(m.promises).then(function(p){try{b.apply(c,p)}catch(q){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+q))}},
function(p){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+p))})});else{h=[];var u=a;d.utils.isArray(a)||(u=[a]);for(var n=0;n<u.length;n++)h.push(f.getSync(u[n]));return h=d.utils.isArray(a)?h:h[0]}};d.extract=function(a,b){var c="",h=function(){for(var q={},A=e.document.getElementsByTagName("META")||[],y=0,E=A.length;y<E;y++){var D=A[y].name||A[y].getAttribute("property")||"";0!==D.length&&(q[D]=A[y].content)}return q}(),
u=function(q){var A=h[q];if(A)return A;A=e.document.getElementsByTagName("META")||[];for(var y=0,E=A.length;y<E;y++){var D=A[y].name||A[y].getAttribute("property")||"";if(q==D)return A[y].content}},n=function(q){return(val=(new RegExp("&"+q+"=([^&]*)")).exec(e.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},m=function(q){return(val=(new RegExp("^"+q+"=.*|;\\s*"+q+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},p=function(q){(q=getElement(q))&&q.nodeType&&1==q.nodeType&&
(q=q.value||q.innerHTML||"");return q.toString().replace(/\n|\r|\s\s+/g,"")||""};try{return b?"meta"==b?c=u(a):"cookie"==b?c=m(a):"param"==b?c=n(a):"content"==b?c=p(a):"var"==b&&(c=e[a]):c=u(a)||m(a)||n(a)||p(a)||e[a]||"",c||""}catch(q){return""}};d.event_param={};if("undefined"==typeof k)var k={exports:{}};return d}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){var e={},B=window,v,f=Array.isArray||function(k){return"[object Array]"===Object.prototype.toString.call(k)};
e.set=function(k,a){};e.get=function(k){};e.remove=function(k){};e.clear=function(){};try{if("localStorage"in B&&B.localStorage){var d=B.localStorage;e.set=function(k,a){var b,c=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(f(k)){var h=0;for(b=k.length;h<b;h++)d.setItem(k[h],"string"===typeof a[h]?a[h]:c.stringify(a[h]))}else d.setItem(k,"string"===typeof a?a:c.stringify(a))};e.get=function(k){if(f(k)){var a={},b;var c=0;for(b=k.length;c<b;c++)a[k[c]]=d.getItem(k[c]);
return a}return d.getItem(k)};e.remove=function(k){if(f(k)){var a;var b=0;for(a=k.length;b<a;b++)d.removeItem(k[b])}else d.removeItem(k)};e.clear=function(){d.clear()};e.all=function(){return d}}}catch(k){}var r={};for(v in e)r[v]=e[v];r.testStorage=function(){try{var k="tk_"+Math.ceil(5E7*Math.random());r.set(k,"test");if("test"===r.get(k))return r.remove(k),!0}catch(a){}return!1};e.utils=r;return window[ensightenOptions.ns].data.local=e}()),window[ensightenOptions.ns].data.defineEngine("cookie",
function(e,B){var v=function(){return v.get.apply(v,arguments)},f=v.utils={isArray:Array.isArray||function(d){return"[object Array]"===Object.prototype.toString.call(d)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(d){return Array.prototype.slice.call(d)},getKeys:Object.keys||function(d){var r=[],k="";for(k in d)d.hasOwnProperty(k)&&r.push(k);return r},escape:function(d){return String(d).replace(/[,;"\\=\s%]/g,function(r){return encodeURIComponent(r)})},retrieve:function(d,
r){return null==d?r:d},getAllCookies:function(){if(""===e.cookie)return{};for(var d=e.cookie.split("; "),r={},k=0,a=d.length;k<a;k++){var b=d[k].split("=");r[decodeURIComponent(b[0])]=decodeURIComponent(b[1])}return r},set:function(d,r,k){k=k||-1;if(f.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&v.set(a,d[a],r);else if(f.isArray(d)){var b;a=0;for(b=d.length;a<b;a++)v.set(d[a],r[a],k)}else{a=k.expires!==B?k.expires:v.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=f.isPlainObject(a)&&
"toGMTString"in a?";expires="+a.toGMTString():f.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;b=(b=k.path||v.defaults.path)?";path="+b:"";var c=k.domain||v.defaults.domain;c=c?";domain="+c:"";k=k.secure||v.defaults.secure?";secure":"";e.cookie=f.escape(d)+"="+f.escape(r)+a+b+c+k}},get:function(d,r){r=r||B;var k=f.getAllCookies();if(f.isArray(d)){for(var a={},b=0,c=d.length;b<c;b++)a[d[b]]=f.retrieve(k[d[b]],r),a[d[b]]===B&&(a[d[b]]=null);return a}a=f.retrieve(k[d],
r);return a===B?null:a},getGMTString:function(d){var r=new Date;r.setTime(r.getTime()+864E5*d);return r.toGMTString()}};v.defaults={path:"/",expires:f.getGMTString(90)};v.set=function(d,r){f.set(d,r)};v.remove=function(d){d=f.isArray(d)?d:f.toArray(arguments);for(var r=0,k=d.length;r<k;r++)f.set(d[r],"",{expires:-1})};v.clear=function(){return v.remove(f.getKeys(f.getAllCookies()))};v.get=function(d,r){return f.get(d,r)};v.all=function(){return f.getAllCookies()};v.utils=f;return window[ensightenOptions.ns].data.cookie=
v}(document)));

const __public=window[ensightenOptions.ns];
if(!__public.ensEvent||!__public.ensEvent.defined){const r=function(n,k){var d={queue:{},pollQueue:{},max_recur:1E3,pushTrigger:function(a,b){if("[object Array]"===Object.prototype.toString.call(a)){for(var c=0;c<a.length;c++)d.pushTrigger(a[c],b);return!0}if("string"!=typeof a)return!1;this.queue[a]=this.queue[a]||{fn:[]};"function"==typeof b&&this.queue[a].fn.push(b);d.addEventRunTime("eventsAdded",a);return!0},callTrigger:function(a,b,c,p){if("string"!=typeof a)return!1;var e=d.queue[a];if("object"==
typeof e&&e.fn&&e.fn.length){if(0!=e.fireOnFirstSet&&c==k||c!=k&&0!=e.fireOnUpdate)for(var f=b;f<e.fn.length;f++)try{e.fn[f].call(this),d.addEventRunTime("eventsTriggered",a)}catch(q){__public.reportException(q)}e=e.fn.length;__public.testAll();d.queue[a].fn.length>e&&(b>=d.max_recur?__public.reportException({name:"EventTriggerRecursionLimitExceeded",message:"Event - "+a+" trigger reached the max recursion depth limit."}):d.callTrigger(a,e,c,p))}},addEventRunTime:function(a,b){var c=__public.ensEvent;
c[a]=c[a]||{};c[a][b]=c[a][b]||{runTimes:[]};c[a][b].runTimes.push((new Date).getTime())},clearQueue:function(){this.queue={}},getQueue:function(){return this.queue}};let l=!1;const g=[];__public.bindPageSpecificCompletion(function(){for(l=!0;0<g.length;){const a=g.shift();m.trigger(a.name,a.ref)}});let h=!1;var m={add:function(a,b){return d.pushTrigger(a,b)},get:function(a){return d.queue[a]},trigger:function(a,b){if(l)return b=b||n,__public.data=__public.data||{},__public.data.event_param=b||{},
d.callTrigger.call(b||Bootstrapper,a,0);g.push({name:a,ref:b})},initialize:function(){h||(this.extend(d),h=!0)},extend:function(a){h&&__public.reportException({name:"EventExtendException",message:"Event extend was called after event initialization."})},clearQueue:function(){d.clearQueue()},getQueue:function(){return d.getQueue()},defined:!0};return m}(window);Object.assign(__public.ensEvent,r)};

window[ensightenOptions.ns].ensEvent.initialize();
Bootstrapper.dataDefinitionIds = [11202,11235,25397,12104,23528,52314,12619,17791];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var isInIFrame=window.location!=window.parent.location;return isInIFrame},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"Iframe",collection:"global",source:"Manage",priv:"false"},{id:"11202"})},11202)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){if(window.location!=window.parent.location)return 1;else return 0},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"isIFrame",collection:"Booleans",source:"Manage",priv:"false"},{id:"11235"})},11235)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.href},load:"instance",trigger:Bootstrapper.data.afterElementsDownloadedTrigger,dataDefName:"PageURL",collection:"global",source:"Manage",priv:"false"},{id:"12104"})},12104)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){if(typeof dlo!=="undefined"&&(typeof dlo.loc!=="undefined"||typeof dlo.page!=="undefined")&&typeof dlo.user!=="undefined"&&window.location.href.indexOf("loginIframe")===-1)if(dlo.user.isMobile===true)return dlo.page;else return dlo.loc;else if(window.location.href.indexOf("explora")!==
-1)return"static";else if(window.location.href.indexOf("c/product")!==-1)return"productDetail";else if(window.location.href.indexOf("c/buy")!==-1)return"productList";else if(window.location.href.indexOf("c/search")!==-1)return"productList";else if(window.location.href.indexOf("c/browse")!==-1)return"category";else if(window.location.href.indexOf("cart.jsp")!==-1)return"cart";else if(window.location.href.indexOf("invoice.jsp")!==-1)return"invoice";else if(window.location.pathname==="/")return"home";
else if(window.location.href.indexOf("c/promotion")!==-1)return"promotion";else if(window.location.href.indexOf("find/wishlist.jsp")!==-1)return"wishlist";else return"unknown page type"},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"loc",collection:"dlo",source:"Manage",priv:"false"},{id:"12619"})},12619)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){function findCookie(name){var nameEQ=name+"\x3d";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];if(c.indexOf(nameEQ)>=0)return"Y"}return"N"}var ab="N";try{if(findCookie("ihUser")=="N")ab="Y"}catch(e){ab="N"}return ab},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,
dataDefName:"ab",collection:"global",source:"Manage",priv:"false"},{id:"17791"})},17791)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){if(document.querySelector('[rel\x3d"canonical"]')!==null)return document.querySelector('[rel\x3d"canonical"]').href;else return""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"Canonical URL",collection:"global",source:"Manage",priv:"false"},{id:"23528"})},23528)},
-1,-1,-1);Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.title},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"Document Title",collection:"dlo",source:"Manage",priv:"false"},{id:"25397"})},25397)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26encEmail\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"Hashed Email",collection:"Page",source:"Manage",priv:"false"},{id:"52314"})},
52314)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.AF=function(){var g={data:{},_dataConfig:{},logHistory:[],debug:!0,dataObj:function(a){var b=a?[]:"";b.finalized=!1;b.type=a;return b},validateInput:function(a){if("object"!==typeof a||"number"!==typeof a.length)return this.log("Error, input must be type Array");/set|push|call|eval|finalize|join/.test(a[0])||this.log("Error, '"+a[0]+"' is not a valid command");return!0},
storeData:function(a,b,d,c,e){e=this.getConfig(b,d,e);b=this.data[b][d];if(e.finalized)return this.log("Error, cannot modify finalized key '"+d+"'"),b;if("undefined"!==typeof b&&e.multi)return"join"==a?b=b.concat(c):b.push(c),b;e.multi?(d=[c],"join"==a&&(d=[].concat(c))):d=c;return d},getConfig:function(a,b,d,c){a=this._dataConfig[a]||{};c={};return"undefined"==typeof a[b]?(c.multi=d,c.finalized=!1,c):a[b]},store:function(a,b,d,c,e){this.data[b]=this.data[b]||{};this.data[b][d]=this.storeData(a,b,
d,c,e);return this.data[b][d]},parseCode:function(a){return((a||function(){})+"").replace(/^function\s*\(\s*\)\s*\{|\}$/g,"")},callFn:function(a,b,d,c){if("function"==typeof a)if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(a)):eval.call(window,this.parseCode(a));else return a.apply(window,c);else if("function"==typeof this.data[a][b])if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(this.data[a][b])):eval.call(window,this.parseCode(this.data[a][b]));
else return c="object"==typeof c&&"number"==typeof c.length?c:[],this.data[a][b].apply(this.data[a],c);else return this.log("Error, '"+b+"' is not a function")},parse:function(a){if(this.validateInput(a)){a=Array.prototype.slice.call(a,0);var b=a.shift(),d=a.shift(),c=a.shift(),e=a[0];if(/set|push|join/.test(b))return this.store(b,d,c,e,/push|join/.test(b));if(/call|eval/.test(b))return this.callFn(d,c,"eval"==b,a);if("finalize"==b)return a=this._dataConfig[d]=this._dataConfig[d]||{},a=a[c]||{multi:!1},
a.finalized=!0,this._dataConfig[d][c]=a}},log:function(a){this.logHistory.push(a);return this.debug&&"object"==typeof console?console.log(a)&&!1:!1}};if("object"==typeof Bootstrapper.AF&&"[object Array]"!==Object.prototype.toString.call(Bootstrapper.AF))return Bootstrapper.AF;if("[object Array]"===Object.prototype.toString.call(Bootstrapper.AF))for(var h=Bootstrapper.AF,f=0;f<h.length;f++)try{g.parse(h[f])}catch(k){}return{push:function(a){return g.parse(a)}}}();Bootstrapper.ajaxListener=function(){var listeners=
{},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==
detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.Cookies=function(){return{domain:""||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"").split("\x3d");if(e[0]==a)return c?e[1]:decodeURIComponent(e[1])}return""},
set:function(a,c,b){document.cookie=a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+Bootstrapper.Cookies.domain+(/https:/.test(location.protocol)===true?";secure":";");return Bootstrapper.Cookies.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}();Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];
return _private.data},getDataElement:function(i,e){if(typeof this.data[i]=="undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=
d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=
this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},
getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.dataManager.map=function(){return{define:function(n,d){if(Bootstrapper.data)for(i in d){var v=typeof d[i]=="string"?Bootstrapper.data.extract(d[i]):d[i]();Bootstrapper.data.dataManagerPush(i,v,n)}}}}();window.$data=function(a,b){if(typeof b=="string")try{return Bootstrapper.dataManager.getDataElement(a,
b)}catch(e){}else if(typeof a=="string")return Bootstrapper.dataManager.getData()[a]||"";return""};Bootstrapper.bindOnGetServerComponent(function(){var DL=Bootstrapper.dataManager&&Bootstrapper.targetingExtension?Bootstrapper.dataManager.getData():{};if(~document.cookie.indexOf("VTP:enabled"))DL["ensightenVT"]=1;if(Bootstrapper.scDataObj)for(i in DL)Bootstrapper.scDataObj[i]=DL[i]});var ns=window[ensightenOptions.ns];ns.VTconfig=ns.VTconfig||{};ns.VTconfig["DM"]=this.deploymentId;Bootstrapper.dataManager.pushObject=
function(obj,id,name){Bootstrapper.dataManager.push({name:name||id,id:id,data:{}});for(var k in obj)if(obj[k]&&typeof obj[k]!=="function")Bootstrapper.dataManager.addDataElement(id,k,{name:k,get:function(o,key){return function(){return o[key]}}(obj,k)})};(function(){function s(e,t,n){var r=t=="blur"||t=="focus";e.element.addEventListener(t,n,r)}function o(e){e.preventDefault();e.stopPropagation()}function u(t){if(e)return e;if(t.matches)e=t.matches;if(t.webkitMatchesSelector)e=t.webkitMatchesSelector;
if(t.mozMatchesSelector)e=t.mozMatchesSelector;if(t.msMatchesSelector)e=t.msMatchesSelector;if(t.oMatchesSelector)e=t.oMatchesSelector;if(!e)e=p.matchesSelector;return e}function a(e,n,r){if(n=="_root")return r;if(e===r)return;if(u(e).call(e,n))return e;if(e.parentNode){t++;return a(e.parentNode,n,r)}}function f(e,t,n,i){if(!r[e.id])r[e.id]={};if(!r[e.id][t])r[e.id][t]={};if(!r[e.id][t][n])r[e.id][t][n]=[];r[e.id][t][n].push(i)}function l(e,t,n,i){if(!i&&!n){r[e.id][t]={};return}if(!i){delete r[e.id][t][n];
return}for(var s=0;s<r[e.id][t][n].length;s++)if(r[e.id][t][n][s]===i){r[e.id][t][n].pop(s,1);break}}function c(e,n,s){if(!r[e][s])return;var o=n.target||n.srcElement,u,f,l={},c=0,h=0;t=0;for(u in r[e][s])if(r[e][s].hasOwnProperty(u)){f=a(o,u,i[e].element);if(f&&p.matchesEvent(s,i[e].element,f,u=="_root",n)){t++;r[e][s][u].match=f;l[t]=r[e][s][u]}}n.stopPropagation=function(){n.cancelBubble=true};for(c=0;c<=t;c++)if(l[c])for(h=0;h<l[c].length;h++){if(l[c][h].call(l[c].match,n)===false){p.cancel(n);
return}if(n.cancelBubble)return}}function h(e,t,n,i){function u(e){return function(t){c(s,t,e)}}if(!(e instanceof Array))e=[e];if(!n&&typeof t=="function"){n=t;t="_root"}var s=this.id,o;for(o=0;o<e.length;o++){if(!r[s]||!r[s][e[o]])p.addEvent(this,e[o],u(e[o]));if(i){l(this,e[o],t,n);continue}f(this,e[o],t,n)}return this}function p(e,t){if(typeof e=="string"&&typeof t=="function"||typeof t=="string")p(document).on(arguments[0],arguments[1],arguments[2],arguments[3]||false);if(!(this instanceof p)){for(var r in i)if(i[r].element===
e)return i[r];n++;i[n]=new p(e,n);i[n]._on=i[n].on;i[n].on=function(e,t,n,r){var i=typeof t=="function"?t:n,s=typeof t=="function"?n||false:r||false;if(!s)return this._on.call(this,e,t,n);else{var o=[e];if(typeof t=="string")o.push(t);o.push(function(e){return function(t){if(!t.defaultPrevented)Bootstrapper.Delegate.load(this,s);if(typeof t.preventDefault!="undefined")t.preventDefault();else t.returnValue=false;e.call(this)}}(i));this._on.apply(this,o)}};return i[n]}this.element=e;this.id=t}var e,
t=0,n=0,r={},i={};_delay=750;p.prototype.on=function(e,t,n){return h.call(this,e,t,n)};p.prototype.off=function(e,t,n){return h.call(this,e,t,n,true)};p.matchesSelector=function(){};p.cancel=o;p.addEvent=s;p.matchesEvent=function(){return true};p.load=function(e,t){var n=typeof t=="number"?parseInt(t):750;setTimeout(function(e,t){return function(){if(e.nodeName&&"a"==e.nodeName.toLowerCase()){if(t&&/^javascript\s*:/.test(t))return(new Function(unescape(t))).call(window);else if(e.target&&/_blank|_new/i.test(e.target))return true;
if(t)window.location.href=t}}}(e,e.href||""),n)};Bootstrapper.Delegate=p})();(function(e){var t=e.addEvent;e.addEvent=function(e,n,r){if(e.element.addEventListener)return t(e,n,r);if(n=="focus")n="focusin";if(n=="blur")n="focusout";e.element.attachEvent("on"+n,r)};e.simpleMatchesSelector=function(e){if(e.charAt(0)===".")return(" "+this.className+" ").indexOf(" "+e.slice(1)+" ")>-1;if(e.charAt(0)==="#")return this.id===e.slice(1);return this.tagName.toUpperCase()===e.toUpperCase()};e.matchesSelector=
function(t){if(!~t.indexOf(" ")&&!~t.indexOf("\x3e"))return e.simpleMatchesSelector.call(this,t);else{var n=this,r=t.split(" ").reverse();while(r.length){var i=r.shift();if(~i.indexOf("\x3e")){i=i.split("\x3e").reverse();while(i.length){tempSel=i.shift();if(e.simpleMatchesSelector.call(n,tempSel))n=n.parentNode;else return false}if(!r.length)return true}else while(n!=document){var s=e.simpleMatchesSelector.call(n,i);n=n.parentNode;if(s){if(!r.length)return true;break}}}return false}};e.cancel=function(e){if(e.preventDefault)e.preventDefault();
if(e.stopPropagation)e.stopPropagation();e.returnValue=false;e.cancelBubble=true}})(Bootstrapper.Delegate);Bootstrapper.on=Bootstrapper.Delegate;document.getElementsByClassName=document.getElementsByClassName||function(b){var c=this.all||this.getElementsByTagName("*"),d=[];b=RegExp("(?:^|\\s)"+b+"(?:\\s|$)");for(var a=0;a<c.length;a++)b.test(c[a].className)&&d.push(c[a]);return d};Bootstrapper.getQueryParam=function(key,loc){if(!this.params||loc){var search=loc||window.location.search;var params=
search.replace(/^\?/,""),paramObj={};params=params.split("\x26");for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=paramObj;else return paramObj[key]||""}return this.params[key]||""};Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+
(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();
if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||
document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};
Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<
a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:(true||!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),
content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=
false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL not available")}},store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set","_ensCloak",o)}_log("*** Cloak:Storage updated")},load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");
for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=
o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=
true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=
!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},
500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);
this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");
this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=
!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");
for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},
traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),
25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");
setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p==
"replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p==
"after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=
this.deploymentId;Bootstrapper.propertyWatcher=function(options){var _private={watchers:[]};var _public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;_public.options=options;_public.change=function(oldVal,newVal){};return _public};_private.doChecks=function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i];var p=w.propertyFn?
w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p;if(w.options)if(w.options.stopOnReturn)_private.watchers.splice(i,1)}}_private.resetTimer()};_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);return w};_public={create:_private.addWatcher};_private.doChecks();return _public}();Bootstrapper.one=function(event,element,
callback){var attributeName="data-has-interacted",attributeVal="true";Bootstrapper.on(event,element,function(){if(this.getAttribute(attributeName)!==attributeVal){callback.apply(this,arguments);this.setAttribute(attributeName,attributeVal)}})}},2909691,266038,622);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var testID;var jsessionID=Bootstrapper.data.extract("sessionKey","cookie");var cookieID=Bootstrapper.data.extract("cookieID","cookie");var cartID;var portalID=dlo.portal;try{cartID=parseInt(window.dlo.user.cartID)}catch(e){}if(window.SS_DL!==undefined)testID=window.SS_DL;else testID="No AB Tests";try{if(Bootstrapper.Cookies.get("fs_uid").split("`")[3]!==Bootstrapper.Cookies.get("rememberId")&&
Bootstrapper.Cookies.get("rememberId").length>0)FS.identify(Bootstrapper.Cookies.get("rememberId"));FS.setUserVars({"testID_str":testID,"isMobile_str":"false","portalID_str":portalID,"jsessionID_str":jsessionID,"cookieID_str":cookieID,"cartID_int":cartID})}catch(err){}},3957204,359620,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;try{Bootstrapper.on("click",".esu-email-no-thanks",function(){ga("send","event","Site Links","Subscribe Layer","No Thanks")});Bootstrapper.on("click",".esu-email-submit",function(){ga("send","event","Site Links","Subscribe Layer","Join Now")});Bootstrapper.on("click",".esu-close",function(){ga("send","event","Site Links","Subscribe Layer","Close X")})}catch(err){}},3026094,
619597,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var loc="";if(dlo.loc!==undefined)loc=dlo.loc;Bootstrapper.on("click",".helpButtonEnabled.uiButton",function(){ga("send","event","Site Links","Chat Snap-in",loc);if(typeof SS!=="undefined")SS.EventTrack.rp("Chat Snap-in")});Bootstrapper.on("click",".snapins-product",function(){ga("send","event","Site Links","Chat - Product",loc)});Bootstrapper.on("click",".snapins-order",function(){ga("send",
"event","Site Links","Chat - Order",loc)})},3907307,646901,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(){window.LUX=function(){function n(){return Date.now?Date.now():+new Date}var r,t=n(),a=window.performance||{},e=a.timing||{activationStart:0,navigationStart:(null===(r=window.LUX)||void 0===r?void 0:r.ns)||t};function i(){return a.now?(r=a.now(),Math.floor(r)):n()-e.navigationStart;var r}(LUX=window.LUX||{}).ac=[],LUX.addData=function(n,r){return LUX.cmd(["addData",
n,r])},LUX.cmd=function(n){return LUX.ac.push(n)},LUX.getDebug=function(){return[[t,0,[]]]},LUX.init=function(){return LUX.cmd(["init"])},LUX.mark=function(){for(var n=[],r=0;r<arguments.length;r++)n[r]=arguments[r];if(a.mark)return a.mark.apply(a,n);var t=n[0],e=n[1]||{};void 0===e.startTime&&(e.startTime=i());LUX.cmd(["mark",t,e])},LUX.markLoadTime=function(){return LUX.cmd(["markLoadTime",i()])},LUX.measure=function(){for(var n=[],r=0;r<arguments.length;r++)n[r]=arguments[r];if(a.measure)return a.measure.apply(a,
n);var t,e=n[0],o=n[1],u=n[2];t="object"==typeof o?n[1]:{start:o,end:u};t.duration||t.end||(t.end=i());LUX.cmd(["measure",e,t])},LUX.send=function(){return LUX.cmd(["send"])},LUX.ns=t;var o=LUX;return window.LUX_ae=[],window.addEventListener("error",function(n){window.LUX_ae.push(n)}),o}();var isLUXLoaded=false;window.handlePerformanceEvent=function(eventData){if(!isLUXLoaded)return;if(eventData.performance_type==="SPA_TRANSITION_START"){window.LUX.send();window.LUX.init()}if(eventData.performance_type===
"SPA_TRANSITION_END")window.LUX.markLoadTime()};function attemptLoadLux(){var retryCount=0;function tryLoad(){var url=window.location.href.replace(window.location.origin,"");var isValidUrl=!/^\/spanish|jsessionid/.test(url);var isValidPage=window.dlo&&["home","category","productList","productDetail","cart"].indexOf(dlo.loc)!==-1;var isValidUser=Bootstrapper.data.extract("ihUser","cookie")!=="null";if(isValidUrl&&isValidPage&&isValidUser){var script=document.createElement("script");script.type="text/javascript";
script.src="https://cdn.speedcurve.com/js/lux.js?id\x3d150015";script.crossOrigin="anonymous";script.onload=function(){isLUXLoaded=true};document.head.appendChild(script);return}retryCount++;if(retryCount<3)setTimeout(tryLoad,500)}tryLoad()}attemptLoadLux()})()},4176711,739854,24);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();